#!/bin/bash
hex_add_1(){
local mac_curr=$1
local mac_curr_rev=`echo $mac_curr | rev`
local flag=1
local result=""

for i in {0..11}
do
        i=${mac_curr_rev:$i:1}
        if [ $flag -eq 1 ]
        then
                case $i in
                [0-8])
                        let i++
                ;;
                9)
                        i=A
                ;;
                a|A)
                        i=B
                ;;
                b|B)
                        i=C
                ;;
                c|C)
                        i=D
                ;
                d|D)
                        i=E
                ;;
                e|E)
                        i=F
                ;;
                f|F)
                        i=0
                        flag=1
                ;;
                esac
                [[ $i != 0 ]]&&flag=0
        fi

        result=$i$result
done
echo $result

unset mac_curr
unset mac_curr_rev
unset i
unset flag
unset result
}
